foreach(required IN ITEMS BAKED_ROOT GENERATED_ROOT MANIFEST)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()

set(header "${GENERATED_ROOT}/assets/asset_ids.gen.h")
if(NOT EXISTS "${header}")
    message(FATAL_ERROR "generated asset catalog is missing: ${header}")
endif()
file(READ "${header}" header_text)
if(NOT header_text MATCHES "ASSET_UV_TEST_TGA" OR
   NOT header_text MATCHES "MOBA_ASSET_CATALOG_ENTRIES" OR
   NOT header_text MATCHES "MOBA_ASSET_CATALOG")
    message(FATAL_ERROR "generated asset catalog is incomplete")
endif()

if(NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "generated source manifest is missing: ${MANIFEST}")
endif()
file(READ "${MANIFEST}" manifest_text)
string(REPLACE "\r\n" "\n" manifest_text "${manifest_text}")
string(REGEX REPLACE "\n$" "" manifest_text "${manifest_text}")
if(manifest_text STREQUAL "")
    message(FATAL_ERROR "generated source manifest is empty")
endif()
string(REPLACE "\n" ";" manifest_entries "${manifest_text}")
foreach(logical_path IN LISTS manifest_entries)
    set(baked "${BAKED_ROOT}/${logical_path}.mba")
    if(NOT EXISTS "${baked}")
        message(FATAL_ERROR "baked content is missing: ${baked}")
    endif()
    file(SIZE "${baked}" baked_bytes)
    if(baked_bytes LESS 33)
        message(FATAL_ERROR "baked content is too small: ${baked}")
    endif()
endforeach()

message(STATUS "content outputs: generated catalog and all manifest assets exist")
