#!/usr/bin/env python3
"""Independent encoder for the ADR-0016 typed record goldens.

Re-implements the .mba record container and the proto-design section 3.3 record
bodies from the authored text sources so the C++ codecs and the cooker are
cross-checked against a second implementation. Writes:
  assets/content/golden/{hero_test,tower_test,gold_rule}.mba
  tests/assets/content_golden.inc

Usage: python tests/assets/content_golden.py   (from the repo root)
"""
from __future__ import annotations

import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / "assets" / "content"
FNV_OFFSET, FNV_PRIME = 14695981039346656037, 1099511628211

KIND = {"hero": 5, "objective": 6, "economy": 7, "map": 8}
TARGET_MODE = {"point": 1, "entity": 2, "self": 3, "area": 4}
EFFECT_TYPE = {"projectile_damage": 1, "self_heal": 2, "area_slow": 3}
OBJECTIVE_KIND = {"tower": 1, "core": 2}
TARGET_POLICY = {"nearest": 0, "lowest_health": 1, "hero_first": 2}
AWARD_KIND = {"gold": 1, "xp": 2}
SOURCE_KIND = {"hero_kill": 1, "objective_damage": 2, "objective_destroy": 3}


def asset_id(path: str) -> int:
    """ADR-0010 canonical id: lowercase, '/' separators, FNV-1a/64 over the bytes."""
    norm = "/".join(seg for seg in path.replace("\\", "/").lower().split("/") if seg and seg != ".")
    h = FNV_OFFSET
    for b in norm.encode("ascii"):
        h = ((h ^ b) * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return h


def load_kv(path: Path) -> dict[str, str]:
    kv: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        k, v = (s.strip() for s in line.split("=", 1))
        assert k not in kv, k
        kv[k] = v
    return kv


def enum(kv: dict[str, str], key: str, table: dict[str, int], default: int | None = None) -> int:
    if key not in kv:
        assert default is not None, key
        return default
    v = kv[key]
    return table[v] if v in table else int(v)


def num(kv: dict[str, str], key: str, default: int | None = None) -> int:
    if key not in kv:
        assert default is not None, key
        return default
    return int(kv[key])


def encode_hero(kv: dict[str, str]) -> bytes:
    actions = []
    i = 0
    while f"action.{i}.id" in kv:
        p = f"action.{i}."
        effects = []
        j = 0
        while f"{p}effect.{j}.type" in kv:
            ep = f"{p}effect.{j}."
            effects.append(struct.pack("<BBHiii", enum(kv, ep + "type", EFFECT_TYPE), 0,
                                       num(kv, ep + "duration_ticks", 0), num(kv, ep + "magnitude"),
                                       num(kv, ep + "radius_q16", 0), num(kv, ep + "scalar_q16", 0)))
            j += 1
        actions.append(struct.pack("<QBBHIIIii", asset_id(kv[p + "id"]), num(kv, p + "slot", i),
                                   enum(kv, p + "target_mode", TARGET_MODE), len(effects),
                                   num(kv, p + "cooldown_ticks"), num(kv, p + "cast_time_ticks", 0),
                                   num(kv, p + "resource_cost", 0), num(kv, p + "range_q16", 0),
                                   num(kv, p + "projectile_speed_q16", 0)) + b"".join(effects))
        i += 1
    head = struct.pack("<IQiiiHH", num(kv, "schema_version", 1), asset_id(kv["hero_id"]),
                       num(kv, "max_health"), num(kv, "move_speed_q16"), num(kv, "attack_range_q16"),
                       len(actions), 0)
    return head + b"".join(actions)


def encode_objective(kv: dict[str, str]) -> bytes:
    return struct.pack("<QBBHiiB3s", asset_id(kv["objective_id"]), num(kv, "owner_team_id"),
                       enum(kv, "kind", OBJECTIVE_KIND), 0, num(kv, "max_health"), num(kv, "armor", 0),
                       enum(kv, "target_policy", TARGET_POLICY, 0), b"\0\0\0")


def encode_economy(kv: dict[str, str]) -> bytes:
    return struct.pack("<BBHI", enum(kv, "award_kind", AWARD_KIND), enum(kv, "source_kind", SOURCE_KIND),
                       0, num(kv, "award_amount"))


def container(kind: int, asset_path: str, body: bytes) -> bytes:
    payload = struct.pack("<IIII", kind, 1, len(body), 0) + body
    header = struct.pack("<IIIIQII", 0x0041424D, 1, kind, len(payload), asset_id(asset_path), 0, 0)
    return header + payload


RECORDS = [
    ("hero_test", "hero", "hero_test.mba", encode_hero),
    ("tower_test", "objective", "objectives/tower_a.mba", encode_objective),
    ("gold_rule", "economy", "economy/gold_hero_kill.mba", encode_economy),
]


def main() -> None:
    (CONTENT / "golden").mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by tests/assets/content_golden.py - do not edit."]
    for name, kind, asset_path, fn in RECORDS:
        data = container(KIND[kind], asset_path, fn(load_kv(CONTENT / f"{name}.txt")))
        (CONTENT / "golden" / f"{name}.mba").write_bytes(data)
        ident = "CONTENT_GOLDEN_" + name.upper()
        lines.append(f"static const uint8_t {ident}[{len(data)}] = {{")
        for i in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
        lines.append("};")
        print(f"wrote assets/content/golden/{name}.mba ({len(data)} bytes)")
    (ROOT / "tests" / "assets" / "content_golden.inc").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote tests/assets/content_golden.inc")


if __name__ == "__main__":
    main()
