#!/usr/bin/env python3
"""Independent generator for the map goldens.

Writes assets/maps/lane_test.mapdesc + tests/sim/map_golden.inc (M5.0) and
assets/maps/lane_slice.mapdesc + tests/sim/lane_slice_golden.inc (M5.3) from the
same descriptions tests/sim/map_tests.cpp and tests/sim/lane_objectives_tests.cpp
author through the C++ API, so the C++ encoder is cross-checked against a second
implementation of the slate-moba-proto-design.md section 3.2 field order.

Usage: python tests/sim/map_golden.py   (from the repo root)
"""
from __future__ import annotations

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

WALKABLE, BLOCKED, LANE, SPAWN, OBJECTIVE, BLOCK_VISION, RAMP = 1, 2, 4, 8, 16, 32, 64
FLAGS = {
    ".": WALKABLE,
    "#": BLOCKED,
    "L": WALKABLE | LANE,
    "S": WALKABLE | LANE | SPAWN,
    "O": WALKABLE | OBJECTIVE,
    "R": WALKABLE | RAMP,
    "V": BLOCKED | BLOCK_VISION,
}

# --- M5.0 lane_test: the 8x8 map map_tests.cpp authors ---------------------------
LANE_TEST_ROWS = [
    "S.L.....",
    ".#L.#...",
    "..L.....",
    "..LLLL..",
    ".....L..",
    "#V...L.R",
    ".....L..",
    ".....LOS",
]
LANE_TEST_MAP_ID = 0x0123456789ABCDEF
LANE_TEST_CELL_SIZE_Q16 = 32768  # 0.5 u
LANE_TEST_LANE = (1, 900, 300, 0x00C0FFEE00C0FFEE, [0, 2, 10, 18, 26, 27, 28, 29])

# --- M5.3 lane_slice: one straight lane, two spawns, four objective cells --------
# Row y=3 is the lane from the west spawn (cell 24) to the east spawn (cell 31).
# Row y=2 carries each team's core at the outer column and its tower two cells in.
LANE_SLICE_ROWS = [
    "........",
    "........",
    "O.O..O.O",
    "SLLLLLLS",
    "........",
    "........",
    "........",
    "........",
]
LANE_SLICE_MAP_ID = 0x00000000005ACE01
LANE_SLICE_CELL_SIZE_Q16 = 65536  # 1.0 u, so one waypoint step is one world unit
LANE_SLICE_LANE = (1, 20, 5, 0x00BADC0DE0000001, [24, 25, 26, 27, 28, 29, 30, 31])


def encode(rows, map_id: int, cell_size_q16: int, lane) -> bytes:
    width, height = len(rows[0]), len(rows)
    out = bytearray(b"MAPD")
    out += struct.pack("<IQHHiI", 1, map_id, width, height, cell_size_q16, width * height)
    for row in rows:
        for c in row:
            cost = 3 if c == "R" else 1
            hgt = 1 if c == "R" else 0
            out += struct.pack("<BBh", FLAGS[c], cost, hgt)
    lane_id, interval, first, archetype, waypoints = lane
    out += struct.pack("<H", 1)
    out += struct.pack("<BBHIQ", lane_id, len(waypoints), interval, first, archetype)
    for wp in waypoints:
        out += struct.pack("<H", wp)
    return bytes(out)


def emit(data: bytes, mapdesc: Path, include: Path, symbol: str) -> None:
    mapdesc.parent.mkdir(parents=True, exist_ok=True)
    mapdesc.write_bytes(data)
    lines = ["// Generated by tests/sim/map_golden.py - do not edit.",
             f"static const uint8_t {symbol}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    include.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {mapdesc} ({len(data)} bytes) and {include}")


def main() -> None:
    emit(encode(LANE_TEST_ROWS, LANE_TEST_MAP_ID, LANE_TEST_CELL_SIZE_Q16, LANE_TEST_LANE),
         ROOT / "assets" / "maps" / "lane_test.mapdesc",
         ROOT / "tests" / "sim" / "map_golden.inc",
         "MAP_GOLDEN_MAPDESC")
    emit(encode(LANE_SLICE_ROWS, LANE_SLICE_MAP_ID, LANE_SLICE_CELL_SIZE_Q16, LANE_SLICE_LANE),
         ROOT / "assets" / "maps" / "lane_slice.mapdesc",
         ROOT / "tests" / "sim" / "lane_slice_golden.inc",
         "LANE_SLICE_MAPDESC")


if __name__ == "__main__":
    main()
