#!/usr/bin/env python3
"""Independent generator for the M5.0 map golden.

Writes assets/maps/lane_test.mapdesc and tests/sim/map_golden.inc from the same
8x8 description that tests/sim/map_tests.cpp authors through the C++ API, so the
C++ encoder is cross-checked against a second implementation of the
slate-moba-proto-design.md section 3.2 field order.

Usage: python tests/sim/map_golden.py   (from the repo root)
"""
from __future__ import annotations

import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

WALKABLE, BLOCKED, LANE, SPAWN, OBJECTIVE, BLOCK_VISION, RAMP = 1, 2, 4, 8, 16, 32, 64
FLAGS = {
    ".": WALKABLE,
    "#": BLOCKED,
    "L": WALKABLE | LANE,
    "S": WALKABLE | LANE | SPAWN,
    "O": WALKABLE | OBJECTIVE,
    "R": WALKABLE | RAMP,
    "V": BLOCKED | BLOCK_VISION,
}
ROWS = [
    "S.L.....",
    ".#L.#...",
    "..L.....",
    "..LLLL..",
    ".....L..",
    "#V...L.R",
    ".....L..",
    ".....LOS",
]
MAP_ID = 0x0123456789ABCDEF
CELL_SIZE_Q16 = 32768  # 0.5 u
LANE = (1, 900, 300, 0x00C0FFEE00C0FFEE, [0, 2, 10, 18, 26, 27, 28, 29])


def encode() -> bytes:
    width, height = 8, 8
    out = bytearray(b"MAPD")
    out += struct.pack("<IQHHiI", 1, MAP_ID, width, height, CELL_SIZE_Q16, width * height)
    for row in ROWS:
        for c in row:
            cost = 3 if c == "R" else 1
            hgt = 1 if c == "R" else 0
            out += struct.pack("<BBh", FLAGS[c], cost, hgt)
    lane_id, interval, first, archetype, waypoints = LANE
    out += struct.pack("<H", 1)
    out += struct.pack("<BBHIQ", lane_id, len(waypoints), interval, first, archetype)
    for wp in waypoints:
        out += struct.pack("<H", wp)
    return bytes(out)


def main() -> None:
    data = encode()
    golden = ROOT / "assets" / "maps" / "lane_test.mapdesc"
    golden.parent.mkdir(parents=True, exist_ok=True)
    golden.write_bytes(data)
    lines = ["// Generated by tests/sim/map_golden.py - do not edit.",
             f"static const uint8_t MAP_GOLDEN_MAPDESC[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    (ROOT / "tests" / "sim" / "map_golden.inc").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {golden} ({len(data)} bytes) and tests/sim/map_golden.inc")


if __name__ == "__main__":
    main()
